# code: language=esphome
esphome:
  name: garaz
  friendly_name: Brama garazowa

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: garaz
    password: 7yUS2NjjC2BuDrW7

captive_portal:

sensor:
  - platform: wifi_signal
    name: RSSI
    update_interval: 60s
    id: wifi_signal_strength

  - platform: adc
    pin: 3
    # name: Current
    attenuation: auto
    id: curent_sensor
    update_interval: 50ms
    entity_category: diagnostic
    device_class: current
    unit_of_measurement: A
    filters:
      - multiply: 1.2
      - sliding_window_moving_average:
          window_size: 4
          send_every: 2
          send_first_at: 2

binary_sensor:
  # - platform: gpio
  #   name: Przycisk
  #   entity_category: diagnostic
  #   pin:
  #     number: 10
  #     mode: INPUT_PULLUP
  #     inverted: true
  #   id: push_button
  #   on_click:
  #     min_length: 200ms
  #     then:
  #       cover.toggle: garage_door
  - platform: gpio
    name: Pilot/przycisk
    entity_category: diagnostic
    pin:
      number: 7
      mode: INPUT_PULLUP
      inverted: true
    id: radio_button
    on_press:
      then:
        cover.toggle: garage_door

switch:
  - platform: gpio
    pin: 1
    id: relay_open
    restore_mode: ALWAYS_OFF
    interlock: &interlock [relay_open, relay_close]
    interlock_wait_time: 0.5s

  - platform: gpio
    pin: 0
    id: relay_close
    restore_mode: ALWAYS_OFF
    interlock: *interlock
    interlock_wait_time: 0.5s

cover:
  - platform: current_based
    id: garage_door
    name: Garaż
    device_class: garage
    open_sensor: curent_sensor
    close_sensor: curent_sensor
    open_moving_current_threshold: 0.2
    close_moving_current_threshold: 0.2
    open_obstacle_current_threshold: 1.8
    close_obstacle_current_threshold: 1.8
    open_action:
      - switch.turn_on: relay_open
    close_action:
      - switch.turn_on: relay_close
    stop_action:
      - switch.turn_off: relay_open
      - switch.turn_off: relay_close
    malfunction_detection: false
    max_duration: 45s
    open_duration: 22s
    close_duration: 21s
