# code: language=esphome
esphome:
  name: garaz
  friendly_name: Brama garazowa
  # on_boot:
  #   priority: -200
  #   then:
  #     - cover.close: garage_door

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: garaz
    password: 7yUS2NjjC2BuDrW7

captive_portal:

globals:
  - id: disable_button
    type: bool
    restore_value: true
    initial_value: "false"
  - id: disable_remote
    type: bool
    restore_value: true
    initial_value: "false"

sensor:
  - platform: wifi_signal
    name: RSSI
    update_interval: 60s
    id: wifi_signal_strength

  - platform: adc
    pin: 3
    # name: Current
    attenuation: auto
    id: curent_sensor
    update_interval: 50ms
    entity_category: diagnostic
    device_class: current
    unit_of_measurement: A
    filters:
      - multiply: 1.2
      - sliding_window_moving_average:
          window_size: 4
          send_every: 2
          send_first_at: 2

binary_sensor:
  - platform: gpio
    name: Przycisk
    entity_category: diagnostic
    icon: mdi:electric-switch
    pin:
      number: 10
      mode: INPUT_PULLUP
      inverted: true
    id: push_button
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        if:
          condition:
            lambda: 'return !id(disable_button);'
          then:
            - cover.toggle: garage_door

  - platform: gpio
    name: Pilot
    entity_category: diagnostic
    icon: mdi:electric-switch
    pin:
      number: 7
      mode: INPUT_PULLUP
      inverted: true
    id: radio_button
    filters:
      - delayed_on_off: 200ms
    on_press:
      then:
        if:
          condition:
            lambda: 'return !id(disable_remote);'
          then:
            - cover.toggle: garage_door

switch:
  - platform: gpio
    pin: 1
    id: relay_open
    restore_mode: ALWAYS_OFF
    interlock: &interlock [relay_open, relay_close]
    interlock_wait_time: 0.5s

  - platform: gpio
    pin: 0
    id: relay_close
    restore_mode: ALWAYS_OFF
    interlock: *interlock
    interlock_wait_time: 0.5s

  - platform: template
    name: Blokada przycisku
    entity_category: config
    icon: mdi:lock
    lambda: return id(disable_button);
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - globals.set:
          id: disable_button
          value: "true"
    turn_off_action:
      - globals.set:
          id: disable_button
          value: "false"

  - platform: template
    name: Blokada pilota
    entity_category: config
    icon: mdi:lock
    lambda: return id(disable_remote);
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - globals.set:
          id: disable_remote
          value: "true"
    turn_off_action:
      - globals.set:
          id: disable_remote
          value: "false"

cover:
  - platform: current_based
    id: garage_door
    name: Garaż
    device_class: garage
    open_sensor: curent_sensor
    close_sensor: curent_sensor
    open_moving_current_threshold: 0.2
    close_moving_current_threshold: 0.2
    open_obstacle_current_threshold: 1.8
    close_obstacle_current_threshold: 1.8
    open_action:
      - switch.turn_on: relay_open
    close_action:
      - switch.turn_on: relay_close
    stop_action:
      - switch.turn_off: relay_open
      - switch.turn_off: relay_close
    malfunction_detection: false
    max_duration: 45s
    open_duration: 22s
    close_duration: 21s
